name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch

env:
  ECR_REPOSITORY: 481665095897.dkr.ecr.us-east-1.amazonaws.com/fastapi-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1

      - name: Build Docker image
        id: build-image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}/fastapi-app:latest .

      - name: Run Trivy vulnerability scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy image --exit-code 1 --severity CRITICAL ${{ env.ECR_REPOSITORY }}/fastapi-app:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.ECR_REPOSITORY }}/fastapi-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Deploy to EKS (Canary)
        run: |
          echo "Deploying to EKS (Canary)"
          kubectl apply -f kubernetes/deployment-canary.yaml

      - name: Wait for health check (Canary)
        run: |
          echo "Waiting for health check on Canary Deployment"
          kubectl rollout status deployment/fastapi-app-canary --timeout=300s

      - name: Rollback if health check fails (Canary)
        if: failure()
        run: |
          echo "Health check failed. Rolling back Canary Deployment"
          kubectl rollout undo deployment/fastapi-app-canary

      - name: Deploy to EKS (Full Deployment)
        run: |
          echo "Deploying to EKS (Full Deployment)"
          kubectl apply -f kubernetes/deployment-full.yaml

      - name: Wait for health check (Full Deployment)
        run: |
          echo "Waiting for health check on Full Deployment"
          kubectl rollout status deployment/fastapi-app --timeout=300s

      - name: Rollback if health check fails (Full Deployment)
        if: failure()
        run: |
          echo "Health check failed. Rolling back Full Deployment"
          kubectl rollout undo deployment/fastapi-app
